version: '3'

services:
  not-todo:
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_HOST: ${DB_HOST}
        NODE_ENV: ${NODE_ENV}
        PORT: 8080
        JWT_SECRET: ${JWT_SECRET}
      depends_on:
        - postgres
      build:
        context: ./
        dockerfile: ./Dockerfile
      image: "joe134/not-todo-server:latest"
      ports:
        - "8080:8080"
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "4000:4000"
    volumes:
      - ./pgdata:/var/lib/postgresql/data